"""Precompute PolicyEngine-US rate-response grid used by the web app.

Scales all four statutory payroll rate parameters (OASDI employee/employer,
HI employee/employer) by a common factor (1 + k) and records the resulting
total payroll tax revenue for 2036. Writes pe-data.json at the repo root.

CBO baseline values (primary deficit, payroll tax revenue) are transcribed
from Table 1-1 of CBO's February 2026 Budget and Economic Outlook
(https://www.cbo.gov/publication/62105) into src/data.ts by hand and are
not regenerated by this script.
"""
from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from policyengine_core.reforms import Reform
from policyengine_us import Microsimulation

SS_RATE = 0.062
HI_RATE = 0.0145
SWEEP_YEAR = 2036
K_GRID = [0.0, 0.10, 0.20, 0.30, 0.40, 0.50]
OUT = Path(__file__).resolve().parents[1] / "pe-data.json"


def make_reform(scale_factor: float, year: int) -> Reform:
    new_ss = SS_RATE * (1 + scale_factor)
    new_hi = HI_RATE * (1 + scale_factor)
    period = f"{year}-01-01.{year}-12-31"
    return Reform.from_dict(
        {
            "gov.irs.payroll.social_security.rate.employee": {period: new_ss},
            "gov.irs.payroll.social_security.rate.employer": {period: new_ss},
            "gov.irs.payroll.medicare.rate.employee": {period: new_hi},
            "gov.irs.payroll.medicare.rate.employer": {period: new_hi},
        },
        "policyengine_us",
    )


def total_payroll_tax_b(sim: Microsimulation, year: int) -> float:
    return (
        sim.calc("employee_payroll_tax", period=year).sum()
        + sim.calc("employer_payroll_tax", period=year).sum()
    ) / 1e9


def policyengine_us_version() -> str:
    try:
        out = subprocess.check_output(
            ["pip", "show", "policyengine-us"], text=True, stderr=subprocess.DEVNULL
        )
        for line in out.splitlines():
            if line.startswith("Version:"):
                return line.split(":", 1)[1].strip()
    except Exception:
        pass
    return "unknown"


def main() -> None:
    print(f"Rate response grid at {SWEEP_YEAR}...", flush=True)
    grid = []
    for k in K_GRID:
        sim = Microsimulation() if k == 0.0 else Microsimulation(reform=make_reform(k, SWEEP_YEAR))
        rev = total_payroll_tax_b(sim, SWEEP_YEAR)
        grid.append({"k": round(k, 4), "payroll_b": round(rev, 1)})
        print(f"  k={k:.2f}: ${rev:,.1f}B", flush=True)

    payload = {
        "policyengine_us_version": policyengine_us_version(),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sweep_year": SWEEP_YEAR,
        "rate_response": grid,
    }
    OUT.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"\nSaved {OUT}", flush=True)


if __name__ == "__main__":
    main()
