import {
  CURRENT_COMBINED_RATE,
  RATE_RESPONSE_2036,
  YEARS,
  type YearRow,
} from "./data";

export type PathRow = {
  year: number;
  primaryDeficitB: number;
  cboPayrollB: number;
  reformPayrollB: number;
  primaryDeficitAfterB: number;
  combinedRatePct: number;
};

export type Solution = {
  k: number;
  elasticity: number;
  rows: PathRow[];
  target: YearRow;
};

/**
 * Fit revenue elasticity from the PolicyEngine rate-response grid.
 * Returns the slope of (payroll - payroll₀) / payroll₀ against k, i.e. the
 * percent revenue change per percent rate change. Simple OLS through origin.
 */
export function fitElasticity(): number {
  const base = RATE_RESPONSE_2036[0].payrollB;
  let sumKK = 0;
  let sumKY = 0;
  for (const p of RATE_RESPONSE_2036) {
    const y = (p.payrollB - base) / base;
    sumKK += p.k * p.k;
    sumKY += p.k * y;
  }
  return sumKY / sumKK;
}

/**
 * Solve for the fractional payroll-rate increase k such that, in targetYear,
 * the extra revenue generated by the reform equals CBO's projected primary
 * deficit. Rates rise linearly from +0% in (startYear − 1) to +k in
 * targetYear.
 */
export function solvePath(startYear: number, targetYear: number): Solution {
  const target = YEARS.find((r) => r.year === targetYear);
  if (!target) throw new Error(`No data for ${targetYear}`);

  const elasticity = fitElasticity();
  const k = target.primaryDeficitB / (target.cboPayrollB * elasticity);
  const span = targetYear - (startYear - 1);

  const rows: PathRow[] = YEARS.filter((r) => r.year >= startYear - 1).map(
    (r) => {
      const progress = Math.max(0, Math.min(1, (r.year - (startYear - 1)) / span));
      const kYear = k * progress;
      const extraRev = r.cboPayrollB * kYear * elasticity;
      return {
        year: r.year,
        primaryDeficitB: r.primaryDeficitB,
        cboPayrollB: r.cboPayrollB,
        reformPayrollB: r.cboPayrollB + extraRev,
        primaryDeficitAfterB: r.primaryDeficitB - extraRev,
        combinedRatePct: CURRENT_COMBINED_RATE * (1 + kYear) * 100,
      };
    },
  );

  return { k, elasticity, rows, target };
}

export function fmtB(x: number): string {
  const sign = x < 0 ? "−" : "";
  return `${sign}$${Math.abs(x).toFixed(0)}B`;
}

export function fmtBSigned(x: number): string {
  const sign = x >= 0 ? "+" : "−";
  return `${sign}$${Math.abs(x).toFixed(0)}B`;
}
